### ISSUE TITLE
Usage examples to send the SMS

### ISSUE THREAD

**Issue by ajsb85** [CamposErik/example-library-sms-silent#2]
Hi, @CamposErik 

Choose the most simple library for you to send the SMS and add it to the app example.
When the app is already working with both libraries (Send and Read SMS).
Let's add the changes of the silence ping.

# Example 1

Source code:
https://github.com/tkporter/react-native-sms

```JavaScript
SendSMS.send({
  body: 'The default body of the SMS!',
  recipients: ['0123456789', '9876543210'],
  successTypes: ['sent', 'queued'],
  allowAndroidSendWithoutReadPermission: true
}, (completed, cancelled, error) => {
  console.log('SMS Callback: completed: ' + completed + ' cancelled: ' + cancelled + 'error: ' + error);
});
```

# Example 2

Source code:
https://github.com/yeyintkoko/react-native-sms-x

```JavaScript
SendSMS.send(123, "+95912345678", "Hey.., this is me!\nGood to see you. Have a nice day.",
  (msg) => {
    console.log(msg);
  }
);
```
Reference: #1

**Comment by CamposErik** [comment]
Okey, I include the example 2 code in our library and it worked for one moment, it send two message, after some changes, it doesnt get the permissions correctly. 

I will let the commit here where I include the code and close this issue.

[https://github.com/CamposErik/example-library-sms-silent/commit/52d4a01e9d25cae0cd7575f221003032f8234606](url)
